name: flutter_web_qrcode_scanner
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/moho4141/flutter_web_qrcode_scanner

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebQrcodeScannerWeb
        fileName: flutter_web_qrcode_scanner_web.dart