name: flutter_web_qrcode_scanner
description: Camera-based QR code scanning for Flutter-Web
version: 1.0.2
homepage: https://github.com/moho4141/flutter_web_qrcode_scanner

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebQrcodeScannerWeb
        fileName: flutter_web_qrcode_scanner_web.dart